CREATE TABLE IF NOT EXISTS cms_content (
  id INT PRIMARY KEY AUTO_INCREMENT,
  page VARCHAR(100) NOT NULL UNIQUE,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


